### ISSUE TITLE
Kilopp segfaulting

### ISSUE THREAD

**Issue by maths-lover** [r-darwish/kilopp#1]
Hello there, I git cloned kilopp repo today, and was trying it until I saw the segfault.

Reason: _I don't know yet_

Steps to reproduce: Follow this [screencast](https://asciinema.org/a/346710)

**Comment by maths-lover** [comment]
I'm still not sure about the reason, but maybe this can help?

---
![image](https://user-images.githubusercontent.com/25811797/87178861-798bb400-c2fb-11ea-9030-3d296bdcd916.png)

**Comment by r-darwish** [comment]
I fixed the segfault but the screenshot you posted seems like a different issue. How did you produce the issue in the screenshot? Can you perhaps upload the core dump?
